import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': '#1a5c2a',
        'secondary': '#835500',
        'surface-variant': '#e0e3de',
        'surface-container-highest': '#e0e3de',
        'secondary-fixed': '#ffddb4',
        'on-primary': '#ffffff',
        'primary-fixed': '#aef3b1',
        'secondary-container': '#feae2c',
        'background': '#f7faf4',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e6e9e3',
        'on-secondary-container': '#6b4500',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#93d697',
        'on-secondary-fixed-variant': '#633f00',
        'surface-container-low': '#f1f5ef',
        'on-secondary': '#ffffff',
        'on-primary-container': '#8fd394',
        'surface-container': '#ecefe9',
        'surface-dim': '#d8dbd5',
        'on-surface': '#191d19',
        'secondary-fixed-dim': '#ffb955',
        'inverse-primary': '#93d697',
        'on-error': '#ffffff',
        'outline-variant': '#c0c9bc',
        'tertiary': '#4b3600',
        'on-background': '#191d19',
        'surface-tint': '#2a6b37',
        'surface': '#f7faf4',
        'on-surface-variant': '#40493f',
        'error-container': '#ffdad6',
        'error': '#ba1a1a',
        'outline': '#717a6f',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#291800',
        'primary': '#004317',
        'on-primary-fixed-variant': '#0c5221',
        'tertiary-fixed': '#ffdfa0',
        'on-tertiary-container': '#e8bd62',
        'on-primary-fixed': '#002108',
        'tertiary-container': '#684c00',
      },
      spacing: {
        'gutter': '16px',
        'base': '8px',
        'sm': '12px',
        'lg': '24px',
        'md': '16px',
        'xs': '4px',
        'xl': '32px',
        'container-margin': '20px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '500' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config